name: Publish Website 

on:
  push:
    branches: [ main ]
  workflow_dispatch:
 
jobs:
  SFTP-Deploy-Action:
    name: SFTP-Deploy-Action

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - run: npm ci
      - run: npm run build --if-present

      - name: SFTP-Deploy-Action
        uses: milanmk/actions-file-deployer@master
        with:
          local-path: ./dist
          remote-protocol: sftp
          remote-host: ${{ secrets.FTP_HOST }}
          remote-user: ${{ secrets.FTP_USER }}
          remote-password: ${{ secrets.FTP_PASSWORD }}
          remote-path: /sub/deploy-test
          remote-port: 22
